language: go
go:
  - 1.6
  - 1.7
  - tip

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install btrfs-tools libdevmapper-dev libgpgme11-dev

install:
  - make install.tools

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - make .gitvalidation
  - make gofmt
  - make lint
  - make integration
  - make docs
